Traceback (most recent call last):
  File "C:\Users\RYZEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\RYZEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RYZEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\RYZEN\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\RYZEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "C:\Users\RYZEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\RYZEN\AppData\Local\Programs\Python\Python312\Lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Visualisasi
plt.figure(figsize=(15, 5))
sns.lineplot(data=df[['xt-3', 'xt-2', 'xt-1', 'xt']])
plt.title('Harga Gula (xt-3, xt-2, xt-1, xt)')
plt.xlabel('Tanggal')
plt.ylabel('Harga Gula (kg)')
plt.xticks(rotation=90)
plt.tight_layout()
plt.show()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Cell [1;32mIn[9], line 2[0m
[0;32m      1[0m [38;5;66;03m# Visualisasi[39;00m
[1;32m----> 2[0m [43mplt[49m[38;5;241m.[39mfigure(figsize[38;5;241m=[39m([38;5;241m15[39m, [38;5;241m5[39m))
[0;32m      3[0m sns[38;5;241m.[39mlineplot(data[38;5;241m=[39mdf[[[38;5;124m'[39m[38;5;124mxt-3[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mxt-2[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mxt-1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mxt[39m[38;5;124m'[39m]])
[0;32m      4[0m plt[38;5;241m.[39mtitle([38;5;124m'[39m[38;5;124mHarga Gula (xt-3, xt-2, xt-1, xt)[39m[38;5;124m'[39m)

[1;31mNameError[0m: name 'plt' is not defined

